# Generated by Django 4.2.11 on 2024-03-15 06:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_tag_alter_lesson_course_lesson_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
